baseURL = "https://adrifaudot.github.io/"
locale = "fr-fr"
title = "Adrien Faudot"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "International Clearing Project"
    url = "/international-clearing-project/"
    weight = 2

  [[menu.main]]
    name = "Publications [ENG]"
    url = "/publications/"
    weight = 3

  [[menu.main]]
    name = "Publications [FR]"
    url = "/publications-fr/"
    weight = 4

  [[menu.main]]
    name = "CV"
    url = "/a-propos/"
    weight = 5